"""empty message

Revision ID: 04fd0fe2ad55
Revises: a8f9337153a4
Create Date: 2021-04-30 03:22:13.044252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04fd0fe2ad55'
down_revision = 'a8f9337153a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_dividents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('exDate', sa.String(), nullable=True),
    sa.Column('paymentDate', sa.String(), nullable=True),
    sa.Column('recordDate', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.compositeFigi'], ),
    sa.ForeignKeyConstraint(['unique_id'], ['symbol.unique_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_dividents_id'), 'stock_dividents', ['id'], unique=False)
    op.create_table('stock_splits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('exDate', sa.String(), nullable=True),
    sa.Column('paymentDate', sa.String(), nullable=True),
    sa.Column('declaredDate', sa.String(), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('tofactor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.compositeFigi'], ),
    sa.ForeignKeyConstraint(['unique_id'], ['symbol.unique_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_splits_id'), 'stock_splits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_splits_id'), table_name='stock_splits')
    op.drop_table('stock_splits')
    op.drop_index(op.f('ix_stock_dividents_id'), table_name='stock_dividents')
    op.drop_table('stock_dividents')
    # ### end Alembic commands ###
