"""empty message

Revision ID: 116415f0af83
Revises: af29a5757b0d
Create Date: 2021-04-30 08:30:33.438063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116415f0af83'
down_revision = 'af29a5757b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'crypto', 'vendor', ['vendor_id'], ['id'])
    op.add_column('indices', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'indices', 'vendor', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'indices', type_='foreignkey')
    op.drop_column('indices', 'vendor_id')
    op.drop_constraint(None, 'crypto', type_='foreignkey')
    op.drop_column('crypto', 'vendor_id')
    # ### end Alembic commands ###
