"""empty message

Revision ID: 15717f7181a4
Revises: c2f0b1e6b2e3
Create Date: 2021-04-30 03:15:51.885162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15717f7181a4'
down_revision = 'c2f0b1e6b2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
