"""empty message

Revision ID: 2341a55838f3
Revises: b33e85b1a987
Create Date: 2021-04-30 05:37:46.718969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2341a55838f3'
down_revision = 'b33e85b1a987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
