"""empty message

Revision ID: 3e364828eb2a
Revises: 2341a55838f3
Create Date: 2021-04-30 05:38:12.377312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e364828eb2a'
down_revision = '2341a55838f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
