"""empty message

Revision ID: 92bbed94121a
Revises: eeec977dc773
Create Date: 2021-04-30 02:53:46.505676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92bbed94121a'
down_revision = 'eeec977dc773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
