"""empty message

Revision ID: 9550395f7310
Revises: 116415f0af83
Create Date: 2021-05-03 01:07:29.751956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9550395f7310'
down_revision = '116415f0af83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
