"""empty message

Revision ID: 9c214bda7dc9
Revises: 04fd0fe2ad55
Create Date: 2021-04-30 05:12:33.518711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c214bda7dc9'
down_revision = '04fd0fe2ad55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
