"""empty message

Revision ID: af29a5757b0d
Revises: d2aecec96c25
Create Date: 2021-04-30 07:38:11.913843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af29a5757b0d'
down_revision = 'd2aecec96c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forex', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forex', 'vendor', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forex', type_='foreignkey')
    op.drop_column('forex', 'vendor_id')
    # ### end Alembic commands ###
