"""empty message

Revision ID: b33e85b1a987
Revises: 423fcf7772a6
Create Date: 2021-04-30 05:25:42.164420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33e85b1a987'
down_revision = '423fcf7772a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
