"""empty message

Revision ID: c2f0b1e6b2e3
Revises: 92bbed94121a
Create Date: 2021-04-30 03:13:42.277453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f0b1e6b2e3'
down_revision = '92bbed94121a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
