"""empty message

Revision ID: d2aecec96c25
Revises: 6f73fd61e159
Create Date: 2021-04-30 05:46:31.857265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2aecec96c25'
down_revision = '6f73fd61e159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'datetime',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('news', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('news', 'keywords',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('news', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('news', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('news', 'symbols',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('news', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('news', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('news', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('news', 'symbols',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('news', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('news', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('news', 'keywords',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('news', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('news', 'datetime',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
