"""empty message

Revision ID: eeec977dc773
Revises: 2ff377f71f20
Create Date: 2021-04-30 02:47:56.933968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eeec977dc773'
down_revision = '2ff377f71f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_splits', 'ratio',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stock_splits', 'tofactor',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'vendor', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor', type_='unique')
    op.alter_column('stock_splits', 'tofactor',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_splits', 'ratio',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
